name: CI

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: latest

      - name: Build local ./fullbasketph
        run: hugo --minify --gc --destination ../public --source ./fullbasketph --themesDir ../.. --baseURL https://fullbasket.github.io/website/

      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public